package services.createPerson;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://services.webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param createPersonRequest
     * @return
     *     returns com.webservice.services.CreatePersonResponse
     */
    @WebMethod
    @WebResult(name = "createPersonResponse", targetNamespace = "")
    @RequestWrapper(localName = "personCreate", targetNamespace = "http://services.webservice.com/", className = "com.webservice.services.PersonCreate")
    @ResponseWrapper(localName = "personCreateResponse", targetNamespace = "http://services.webservice.com/", className = "com.webservice.services.PersonCreateResponse")
    public CreatePersonResponse personCreate(
            @WebParam(name = "createPersonRequest", targetNamespace = "")
                    CreatePersonRequest createPersonRequest);

}
