
package services.searchPerson;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SearchService", targetNamespace = "http://services.webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SearchService {


    /**
     * 
     * @param searchRequest
     * @return
     *     returns com.webservice.services.SearchResponse
     */
    @WebMethod
    @WebResult(name = "searchResponse", targetNamespace = "")
    @RequestWrapper(localName = "createSearch", targetNamespace = "http://services.webservice.com/", className = "com.webservice.services.CreateSearch")
    @ResponseWrapper(localName = "createSearchResponse", targetNamespace = "http://services.webservice.com/", className = "com.webservice.services.CreateSearchResponse")
    public SearchResponse createSearch(
            @WebParam(name = "searchRequest", targetNamespace = "")
                    SearchRequest searchRequest);

}
