
package services.searchPerson;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SearchServiceImplService", targetNamespace = "http://services.webservice.com/", wsdlLocation = "http://localhost:8080/services/SearchService?wsdl")
public class SearchServiceImplService
    extends Service
{

    private final static URL SEARCHSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEARCHSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SEARCHSERVICEIMPLSERVICE_QNAME = new QName("http://services.webservice.com/", "SearchServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/SearchService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEARCHSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SEARCHSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SearchServiceImplService() {
        super(__getWsdlLocation(), SEARCHSERVICEIMPLSERVICE_QNAME);
    }

    public SearchServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHSERVICEIMPLSERVICE_QNAME, features);
    }

    public SearchServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SEARCHSERVICEIMPLSERVICE_QNAME);
    }

    public SearchServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHSERVICEIMPLSERVICE_QNAME, features);
    }

    public SearchServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchService
     */
    @WebEndpoint(name = "SearchServiceImplPort")
    public SearchService getSearchServiceImplPort() {
        return super.getPort(new QName("http://services.webservice.com/", "SearchServiceImplPort"), SearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchService
     */
    @WebEndpoint(name = "SearchServiceImplPort")
    public SearchService getSearchServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.webservice.com/", "SearchServiceImplPort"), SearchService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SEARCHSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SEARCHSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
